# Generated by Django 4.2.6 on 2023-11-01 20:54

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import store.models.cart


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('session_id', models.CharField(default=store.models.cart.generate_cart_session_id, editable=False, max_length=16)),
                ('checkout_complete', models.BooleanField(default=False, editable=False, verbose_name='Cart checked out')),
                ('merged_to', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_with', to='store.cart', verbose_name='Merged carts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('return_policy', ckeditor.fields.RichTextField(blank=True, verbose_name='Return policy')),
                ('shipping_policy', ckeditor.fields.RichTextField(blank=True, verbose_name='Shipping policy')),
                ('tos', ckeditor.fields.RichTextField(blank=True, verbose_name='Terms of service')),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, verbose_name='Privacy policy')),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('pinterest', models.URLField(blank=True)),
                ('name', models.CharField(default='My Store', max_length=100, verbose_name='Store name')),
                ('logo', models.ImageField(upload_to='store', verbose_name='Store logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='store', verbose_name='Favicon')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Store Info',
                'verbose_name_plural': 'Store Info',
            },
        ),
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('image', models.ImageField(upload_to='store/featured/', verbose_name='Image file')),
                ('header', models.TextField(max_length=100, verbose_name='Featured items header')),
                ('slug', models.SlugField(editable=False)),
                ('products', models.ManyToManyField(related_name='featured', to='products.product')),
            ],
            options={
                'verbose_name': 'featured product',
                'verbose_name_plural': 'featured products',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Item quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart item',
                'verbose_name_plural': 'Cart items',
            },
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_cart_product'),
        ),
    ]
