# Generated by Django 4.2.6 on 2023-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(blank=True, help_text='Page description for SEO', max_length=150, verbose_name='Store description'),
        ),
    ]
