# Generated by Django 4.2.5 on 2023-09-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_storeproduct_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ['-date_created'], 'verbose_name': 'Store Product', 'verbose_name_plural': 'Store Products'},
        ),
    ]
