# Generated by Django 4.2.6 on 2023-10-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='check_out_complete',
        ),
        migrations.AddField(
            model_name='cart',
            name='checkout_complete',
            field=models.BooleanField(default=False, editable=False, verbose_name='Cart checked out'),
        ),
    ]
