# Generated by Django 4.2.5 on 2023-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_storeproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='store/product/images/'),
        ),
    ]
