# Generated by Django 4.2.6 on 2023-10-11 15:56

from django.db import migrations, models
import django.db.models.deletion
import store.models.cart


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description_rich'),
        ('store', '0003_remove_cart_check_out_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default=store.models.cart.generate_cart_session_id, editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='products.product', verbose_name='Product'),
        ),
    ]
