# Generated by Django 4.2.5 on 2023-09-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storeproduct_is_listed_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='image',
        ),
    ]
