# Generated by Django 4.2.5 on 2023-10-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_storeproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='StoreProduct',
        ),
    ]
