# Generated by Django 4.2.6 on 2023-10-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
        ('store', '0008_cart_merged_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('image', models.ImageField(upload_to='store/featured/', verbose_name='Image file')),
                ('header', models.CharField(max_length=50, verbose_name='Featured items header')),
                ('product', models.ManyToManyField(related_name='featured', to='products.product')),
            ],
            options={
                'verbose_name': 'featured product',
                'verbose_name_plural': 'featured products',
            },
        ),
    ]
