# Generated by Django 4.2.6 on 2023-10-30 19:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_featuredproducts_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproducts',
            name='header',
            field=tinymce.models.HTMLField(verbose_name='Featured items header'),
        ),
    ]
