# Generated by Django 4.2.6 on 2023-10-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_featuredproducts_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredproducts',
            old_name='product',
            new_name='products',
        ),
    ]
