# Generated by Django 4.2.6 on 2023-10-31 12:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_product_featuredproducts_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproducts',
            name='header',
            field=ckeditor.fields.RichTextField(verbose_name='Featured items header'),
        ),
    ]
