# Generated by Django 4.2.6 on 2023-10-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='favico',
            new_name='favicon',
        ),
    ]
