# Generated by Django 4.2.6 on 2023-11-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_favico_store_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='pinterest',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
