version: "3"

services:
  postgres:
    container_name: ecommerce-postgres
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data

  django:
    container_name: ecommerce-django
    build:
      context: .
      dockerfile: ./.docker/django/Dockerfile
      target: development
    entrypoint: /entrypoint.sh
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./server:/code
      - shared-volume:/var/www
    ports:
      - 8000:8000

  nuxt:
    container_name: nuxt
    build:
      context: .
      dockerfile: ./.docker/nuxt/Dockerfile
      args:
        - DJANGO_URL=${DJANGO_URL}
      target: development
    depends_on:
      - django
    restart: always
    volumes:
      - shared-volume:/var/www
      - ./client:/code
    env_file:
      - .env
    environment:
      - DJANGO_URL
    ports:
      - 3000:3000

  nginx:
    container_name: ecommerce-nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    depends_on:
      - django
      - nuxt
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - shared-volume:/var/www
    env_file:
      - .env
    environment:
      - DOMAIN
      - DJANGO_URL
    ports:
      - 8008:80
    restart: always

volumes:
  shared-volume:
