version: "3"

services:
  postgres:
    container_name: ecommerce-postgres
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data

  django:
    container_name: ecommerce-django
    build:
      context: .
      dockerfile: ./.docker/django/Dockerfile
      target: production
    entrypoint: /entrypoint.sh
    environment:
      - ENVIRONMENT=production
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./server:/code
      - shared-volume:/var/www

  nuxt:
    container_name: ecommerce-nuxt
    build:
      context: .
      dockerfile: ./.docker/nuxt/Dockerfile
      args:
        - DJANGO_URL=${DJANGO_URL}
      target: production
    env_file:
      - .env
    depends_on:
      - django
    environment:
      - NUXT_URL
      - DJANGO_URL

  nginx:
    container_name: ecommerce-nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    depends_on:
      - django
      - nuxt
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - shared-volume:/var/www
    env_file:
      - .env
    environment:
      - NUXT_URL
      - DJANGO_URL

volumes:
  shared-volume:
