# Generated by Django 4.2.6 on 2023-10-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('shipping_address', models.JSONField(editable=False, verbose_name='shipping address')),
                ('billing_address', models.JSONField(editable=False, verbose_name='billing address')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='cities_light.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_addresses', to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text="To be populated by cart's total price at creation time", max_digits=10, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.order', verbose_name='order'),
        ),
    ]
