# Generated by Django 4.2.6 on 2023-11-01 20:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product Category')),
                ('slug', models.SlugField(editable=False)),
                ('banner', models.ImageField(null=True, upload_to='banners/category/')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('list_for_sale', models.BooleanField(default=False, verbose_name='List on store for sale')),
                ('sell_without_stock', models.BooleanField(default=False, help_text='Keep selling if product is out of stock', verbose_name='Sell without stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/products/')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Product SKU')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_rich', ckeditor.fields.RichTextField(blank=True, verbose_name='Description (WYSIWYG)')),
                ('slug', models.SlugField(editable=False)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of products in stock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Sub Category')),
                ('slug', models.SlugField(editable=False)),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbnails/sub-category/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('image', models.ImageField(upload_to=products.models.product_image_upload_path, verbose_name='Image file')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.subcategory', verbose_name='Sub Category'),
        ),
    ]
