# Generated by Django 4.2.6 on 2023-10-10 17:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description_rich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_rich',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description (WYSIWYG)'),
        ),
    ]
