# Generated by Django 4.2.5 on 2023-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(null=True, upload_to='banners/category/'),
        ),
    ]
