# Generated by Django 4.2.5 on 2023-10-04 14:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_list_for_sale_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.product_image_upload_path, verbose_name='Image file'),
        ),
    ]
