# Generated by Django 4.2.6 on 2023-10-31 12:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_rich',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description (WYSIWYG)'),
        ),
    ]
