# Generated by Django 4.2.5 on 2023-10-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Product'),
        ),
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
